SRC_FILES := srcs/channel.cpp \
srcs/commands/nickname.cpp \
srcs/commands/password.cpp \
srcs/commands/username.cpp \
srcs/commands/join.cpp \
srcs/commands/kick.cpp \
srcs/commands/invite.cpp \
srcs/commands/private_message.cpp \
srcs/commands/names.cpp \
srcs/commands/part.cpp \
srcs/commands/capabilities.cpp \
srcs/commands/process_message.cpp \
srcs/commands/topic.cpp \
srcs/commands/quit.cpp \
srcs/commands/pingpong.cpp \
srcs/config.cpp \
srcs/main.cpp \
srcs/untils.cpp \
srcs/client.cpp \
srcs/responseMessage.cpp \
srcs/server.cpp \
